export const IS_LOADING = 'IS_LOADING';
export const LOAD_ACTIVE_USER_SUCCESS = 'LOAD_ACTIVE_USER_SUCCESS';
export const FETCH_FEATURED_NEWS_SUCCESS = 'FETCH_FEATURED_NEWS_SUCCESS';
export const FETCH_GENERAL_NEWS_SUCCESS = 'FETCH_GENERAL_NEWS_SUCCESS';
export const FETCH_FEATURED_NEWS_FAILURE = 'FETCH_FEATURED_NEWS_FAILURE';
export const FETCH_GENERAL_NEWS_FAILURE = 'FETCH_GENERAL_NEWS_FAILURE';

export const FETCH_SEARCH_STOCK_SUCCESS = 'FETCH_SEARCH_STOCK_SUCCESS';
export const FETCH_SEARCH_STOCK_FAILURE = 'FETCH_SEARCH_STOCK_FAILURE';
