export const IS_LOADING = 'IS_LOADING';
export const LOAD_ACTIVE_USER_SUCCESS = 'LOAD_ACTIVE_USER_SUCCESS';
export const FETCH_FEATURED_NEWS_SUCCESS = 'FETCH_FEATURED_NEWS_SUCCESS';
export const FETCH_GENERAL_NEWS_SUCCESS = 'FETCH_GENERAL_NEWS_SUCCESS';
