export const news =  [
    {
        id: 1,
        section: 'Economics',
        title: 'news title1',
        description: 'this is the description',
        author: 'Jon Snow',
        date: '28-01-2019',
    },
    {
        id: 2,
        section: 'Business',
        title: 'news Business',
        description: 'this is the description',
        author: 'Jon Snow',
        date: '28-01-2019',
    },
    {
        section: 'Business',
        title: 'news Business2',
        description: 'this is the description',
        author: 'Jon Snow',
        date: '28-01-2019',
        id: 3,
    },
    {
        section: 'Business',
        title: 'news Business3',
        description: 'this is the description',
        author: 'Jon Snow',
        date: '28-01-2019',
        id: 4,
    },
    {
        section: 'Politics',
        title: 'news Politics',
        description: 'this is the description',
        author: 'Jon Snow',
        date: '28-01-2019',
        id: 5,
    },
    {
        section: 'Business',
        title: 'news title2',
        description: 'this is the description',
        author: 'Jon Snow',
        date: '28-01-2019',
        id: 6,
    },
    {
        section: 'Politics',
        title: 'news title3',
        description: 'this is the description',
        author: 'Jon Snow',
        date: '28-01-2019',
        id: 7,
    },
    {
        section: 'World',
        title: 'news title1',
        description: 'this is the description',
        author: 'Jon Snow',
        date: '28-01-2019',
        id: 8,
    },
    {
        section: 'World',
        title: 'news title2',
        description: 'this is the description',
        author: 'Jon Snow',
        date: '28-01-2019',
        id: 9,
    },
    {
        section: 'World',
        title: 'news title3',
        description: 'this is the description',
        author: 'Jon Snow',
        date: '28-01-2019',
        id: 10,
    },
    {
        id: 11,
        section: 'World',
        title: 'news Business',
        description: 'this is the description',
        author: 'Jon Snow',
        date: '28-01-2019',
    },
];

export const activeNews = [
    {
        section: 'World',
        title: 'news title1',
        description: 'this is the description',
        author: 'Jon Snow',
        date: '28-01-2019',
        id: 8,
    },
    {
        section: 'World',
        title: 'news title2',
        description: 'this is the description',
        author: 'Jon Snow',
        date: '28-01-2019',
        id: 9,
    },
    {
        section: 'World',
        title: 'news title3',
        description: 'this is the description',
        author: 'Jon Snow',
        date: '28-01-2019',
        id: 10,
    },
    {
        id: 11,
        section: 'World',
        title: 'news Business',
        description: 'this is the description',
        author: 'Jon Snow',
        date: '28-01-2019',
    },
];